name       : haskell-conduit-combinators
version    : 1.3.0
release    : 1
source     :
    - https://hackage.haskell.org/package/conduit-combinators-1.3.0/conduit-combinators-1.3.0.tar.gz : 9717d916a0422a7fb7cc262302333269607530d40cd0bea3be947872f906e7d3
license    : MIT
component  : programming.haskell
summary    : Commonly used conduit functions, for both chunked and unchunked data.
description: |
    Commonly used conduit functions, for both chunked and unchunked data. 
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
